import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SAVED_MODELS_DIR = os.path.join(BASE_DIR, 'saved_models')
FRONTEND_DIR = os.path.join(BASE_DIR, 'frontend')

DIGIT_MODEL_PATH = os.path.join(SAVED_MODELS_DIR, 'digit_model.h5')

IMG_SIZE_GENERAL = (224, 224)
IMG_SIZE_DIGIT = (28, 28)

ANIMAL_KEYWORDS = [
    'fish', 'shark', 'ray', 'eel', 'goldfish', 'tench', 'trout', 'salmon', 'sturgeon', 'gar', 'pike',
    'bird', 'hen', 'cock', 'robin', 'jay', 'magpie', 'chickadee', 'grouse', 'ptarmigan', 'quail',
    'partridge', 'ostrich', 'bustard', 'peacock', 'parrot', 'macaw', 'lorikeet', 'cockatoo', 'sulphur',
    'hummingbird', 'toucan', 'drake', 'duck', 'goose', 'swan', 'albatross', 'petrel', 'stork',
    'heron', 'crane', 'flamingo', 'spoonbill', 'ibis', 'pelican', 'king', 'vulture', 'eagle',
    'kite', 'owl', 'hawk', 'falcon', 'kestrel', 'magpie', 'jay', 'crow', 'raven', 'jackdaw',
    'dog', 'hound', 'terrier', 'spaniel', 'retriever', 'shepherd', 'sheepdog', 'collie', 'boxer',
    'mastiff', 'bulldog', 'chihuahua', 'poodle', 'pomeranian', 'keeshond', 'schipperke', 'groenendael',
    'malinois', 'briard', 'kelpie', 'komondor', 'kuvasz', 'puli', 'vizsla', 'weimaraner',
    'wolf', 'wolfhound', 'borzoi', 'saluki', 'whippet', 'greyhound', 'deerhound', 'elkhound',
    'otterhound', 'bloodhound', 'coonhound', 'foxhound', 'basset', 'beagle', 'dachshund', 'basenji',
    'cat', 'tabby', 'tiger', 'cougar', 'puma', 'lynx', 'leopard', 'snow', 'jaguar', 'lion',
    'cheetah', 'panther', 'bobcat', 'lynxcat', 'persian', 'siamese', 'egyptian',
    'horse', 'stallion', 'mare', 'foal', 'pony', 'colt', 'zebra', 'donkey', 'mule',
    'cow', 'ox', 'bull', 'bison', 'buffalo', 'yak', 'cattle', 'steer', 'heifer', 'calf',
    'sheep', 'ram', 'ewe', 'lamb', 'mouflon', 'goat', 'ibex',
    'pig', 'hog', 'swine', 'boar', 'warthog', 'peccary', 'javelina',
    'elephant', 'tusker', 'mammoth', 'rhinoceros', 'hippopotamus', 'hippo',
    'bear', 'grizzly', 'polar', 'panda', 'koala', 'sloth', 'anteater',
    'monkey', 'ape', 'gorilla', 'chimpanzee', 'orangutan', 'gibbon', 'baboon',
    'macaque', 'marmoset', 'tamarin', 'capuchin', 'howler', 'squirrel', 'marmot',
    'lemur', 'indri', 'colobus', 'langur', 'spider', 'patas', 'guenon',
    'kangaroo', 'wallaby', 'wombat', 'opossum', 'possum', 'bandicoot', 'bilby',
    'platypus', 'echidna', 'armadillo', 'pangolin',
    'reptile', 'snake', 'serpent', 'viper', 'cobra', 'python', 'boa', 'anaconda',
    'lizard', 'iguana', 'chameleon', 'gecko', 'skink', 'monitor', 'komodo',
    'turtle', 'tortoise', 'terrapin', 'crocodile', 'alligator', 'gavial',
    'frog', 'toad', 'tadpole', 'salamander', 'newt', 'axolotl', 'eft',
    'insect', 'butterfly', 'moth', 'caterpillar', 'larva', 'beetle', 'ladybug',
    'ladybird', 'fly', 'bee', 'ant', 'wasp', 'grasshopper', 'cricket', 'locust',
    'dragonfly', 'damselfly', 'mantis', 'cockroach', 'termite', 'flea', 'louse',
    'spider', 'scorpion', 'tick', 'centipede', 'millipede', 'tarantula',
    'crab', 'lobster', 'crayfish', 'shrimp', 'prawn', 'barnacle', 'octopus',
    'squid', 'cuttlefish', 'nautilus', 'clam', 'oyster', 'mussel', 'scallop',
    'snail', 'slug', 'conch', 'whelk', 'limpet', 'abalone', 'sea', 'urchin',
    'starfish', 'jellyfish', 'anemone', 'coral', 'sponge',
    'deer', 'elk', 'moose', 'caribou', 'reindeer', 'antelope', 'gazelle',
    'impala', 'wildebeest', 'gnu', 'oryx', 'addax', 'bongo', 'kudu', 'eland',
    'nyala', 'bushbuck', 'sitatunga', 'topi', 'hartebeest', 'dik',
    'camel', 'dromedary', 'llama', 'alpaca', 'guanaco', 'vicuna',
    'giraffe', 'okapi', 'tapir',
    'rabbit', 'bunny', 'hare', 'pika', 'coney',
    'rat', 'mouse', 'rodent', 'hamster', 'gerbil', 'vole', 'gopher',
    'beaver', 'porcupine', 'hedgehog', 'shrew', 'mole',
    'bat', 'vampire', 'flying', 'fox',
    'seal', 'sea', 'walrus', 'otter', 'weasel', 'ferret', 'mink', 'ermine',
    'skunk', 'badger', 'wolverine', 'raccoon', 'coati', 'kinkajou',
    'whale', 'dolphin', 'porpoise', 'narwhal', 'beluga', 'orca', 'killer',
    'manatee', 'dugong',
]

SCENE_KEYWORDS = [
    'beach', 'seashore', 'coast', 'lakeside', 'lakeshore', 'shore', 'shoreline',
    'mountain', 'alp', 'volcano', 'cliff', 'valley', 'gorge', 'canyon', 'ravine',
    'forest', 'wood', 'woodland', 'rainforest', 'jungle', 'grove',
    'desert', 'sand', 'dune', 'oasis',
    'ocean', 'sea', 'wave', 'coral', 'reef', 'lagoon', 'bay',
    'river', 'stream', 'waterfall', 'cascade', 'rapids', 'brook', 'creek',
    'lake', 'pond', 'pool', 'reservoir', 'dam', 'basin',
    'garden', 'park', 'lawn', 'yard', 'greenhouse', 'conservatory',
    'field', 'meadow', 'prairie', 'plain', 'savanna', 'grassland',
    'sky', 'cloud', 'rainbow', 'sunset', 'sunrise', 'twilight', 'dawn',
    'church', 'cathedral', 'chapel', 'monastery', 'temple', 'mosque', 'synagogue', 'pagoda',
    'castle', 'palace', 'fortress', 'citadel', 'fort', 'rampart',
    'building', 'skyscraper', 'tower', 'lighthouse', 'bridge', 'arch',
    'street', 'road', 'highway', 'alley', 'path', 'trail', 'sidewalk',
    'city', 'town', 'village', 'skyline',
    'market', 'shop', 'store', 'restaurant', 'cafe', 'bar', 'pub',
    'library', 'museum', 'theater', 'cinema', 'stadium', 'arena',
    'school', 'university', 'college', 'academy',
    'airport', 'station', 'terminal', 'harbor', 'port', 'pier', 'dock',
    'farm', 'barn', 'silo', 'windmill', 'mill',
    'tent', 'campsite', 'campground',
    'iceberg', 'glacier', 'tundra', 'ice', 'snow', 'frost',
    'island', 'archipelago', 'peninsula', 'cape', 'promontory',
    'cave', 'cavern', 'grotto', 'mine', 'quarry',
    'swamp', 'marsh', 'wetland', 'bog', 'fen', 'moor',
    'vineyard', 'orchard', 'plantation', 'estate',
    'home', 'house', 'cottage', 'cabin', 'mansion', 'villa', 'bungalow',
    'balcony', 'terrace', 'patio', 'courtyard', 'plaza', 'square',
    'fountain', 'pond', 'well', 'spring',
]
